name: calories_check
description: "Smart Nutrition & Diet Planner"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  image_picker: ^1.1.2
  fl_chart: ^0.69.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.2.5
  uuid: ^4.5.1
  supabase_flutter: ^2.3.0
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  image: ^4.5.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/
