name: calories_check
description: "Smart Nutrition & Diet Planner"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1

  # AI (HTTP REST calls to Gemini free tier)
  http: ^1.2.1

  # Storage
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3

  # Image
  image_picker: ^1.1.2

  # UI
  fl_chart: ^0.69.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0

  # URL
  url_launcher: ^6.2.5

  # Utils
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
